osx_image: xcode7.3

sudo: required

language: c

dist: trusty

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

branches:
  only:
    - release

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache
    - build/cache

before_install:
  - mkdir -p /tmp/git-lfs && curl -L http://github.com/github/git-lfs/releases/download/v1.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR=$HOME/.nvm sh
  - source $HOME/.nvm/nvm.sh
  - command -v nvm
  - nvm install 6.4.0
  - nvm use 6.4.0

before_script:
  - npm install --verbose

script:
  - npm run-script build darwin linux
  - npm run-script deploy-github


