os:
  - osx

osx_image: xcode7.3

sudo: required

language: c

git:
  depth: 3

branches:
  only:
    - release

cache:
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.cache
    - build/tools-cache

before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | NVM_DIR=$HOME/.nvm sh
  - source $HOME/.nvm/nvm.sh
  - command -v nvm
  - nvm install 6.5.0
  - nvm use 6.5.0

install:
  - brew update --verbose || true
  - brew install --verbose git-lfs || true; git lfs version
  - brew install --verbose dpkg fakeroot || true; dpkg --version; fakeroot -v
  - brew install --verbose rpm || true; rpm --version

before_script:
  - npm install --verbose
  - npm prune --verbose

script:
  - DEBUG=1 npm run build darwin
  - DEBUG=1 npm run build linux

before_deploy:
  - export DEPLOY_PACKAGES="$(ls ./build/release/*v*.{zip,dmg})"
  - echo "Deploying to GitHub:"
  - echo "${DEPLOY_PACKAGES[@]}"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/24d905038aa07dda37df   # Gitter
    on_success: change
    on_failure: always
    on_start: never

deploy:
  provider: releases
  file_glob: true
  file: "./build/release/*v*.zip"
  skip_cleanup: true
  api_key:
    secure: nncJXVV1dDG0Tqdtm+U2P1kjbBJWJLBmq0T+6oDMjue6JAXai0zR/TlvqjtF844Bz4GkxDnzP8tWS8fxbUki+0cESd7SBrYLsnFicqhwUAu16eTuPX98R92m8EHYjruY+epHu7PRufokSJGhTSU8sMSM+jBWp6T8zw3653P5F5kTZ6hp/ujmji8VQoU/eS4o1wE+z3m99V1DBgnqCqbL3P11QH0RU0/eEkCrZF2YmSu6fXaL3utpyYxfA8g5CGOKMQb9Bte7gBdc9CcKsMVNfpg8Q4X7IB0GB3qfnBN4+DCgXae9ATHATnSQQ0XkJER5Trh7IJEJ5ReD6hrtpERUjNxbJATTgKzi73iFbgdERrdE1LEibmD/rAourVufW5Wd832ATjM9cNFEaovxZv2LTLdtMAdpewc3OmjXE2TAmSv+HjpGWHX0+dI3sTfrvH0sUK1GkydSyBYnKiwOJEdDDzOD8MccTFf+5qwT33aOZwWIwxXopOVxJf+g3eUD80ftZGYlV4OIDMRQWIkOIW/3hdk3voKFC/s47nEE6Aq60qg9f7OvmzUS4oTPLGzj4SJ4fqpGJG8XWYyOJaHiwu2Plbrg1SD0DA+ncXlsJR5rjLSLTgeGshkKQVfPNi2SgaEupZRY139pXiE9izB2K23gVcmaoZD0F0mE/qJZfE0jYLU=
  on:
    repo: sidneys/pb-for-desktop
    branch: release
