os: Visual Studio 2015

platform:
  - x64

branches:
  only:
  - release

clone_depth: 3

version: '{build}-{branch}'

environment:
  DEBUG: electron-windows-installer:main

cache:
  - 'node_modules'
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - cmd: git config --global core.autocrlf input

install:
  # NPM
  - cmd: powershell -Command "Install-Product node '' x64"
  - cmd: npm install --global npm
  - cmd: npm install
  - cmd: npm prune
  # PACKAGE_NAME
  - cmd: node -p "require('./package.json').productName" > PACKAGE_NAME.txt
  - cmd: set /p PACKAGE_NAME=<PACKAGE_NAME.txt
  - cmd: echo %PACKAGE_NAME%
  # PACKAGE_VERSION
  - cmd: node -p "require('./package.json').version" > PACKAGE_VERSION.txt
  - cmd: set /p PACKAGE_VERSION=<PACKAGE_VERSION.txt
  - cmd: echo %PACKAGE_VERSION%


build_script:
  - cmd: npm run-script build win32


artifacts:
  - path: build\release\*.exe
      
    
deploy:
  - provider: GitHub
    tag: v$(PACKAGE_VERSION)
    release: $(PACKAGE_NAME) v$(PACKAGE_VERSION)
    description: $(PACKAGE_NAME)
    auth_token:
      secure: 'pAnN8TLqZboOiNe13JQLQ3xpw7h2+izRIOl8xkEZCj+iCHEWTKusULjcOwaWbOAt'
    artifact: /.*\.exe/
    draft: true
    force_update: true

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/f29f98b58ec67b5f0f59
    method: GET
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
