os: Visual Studio 2015

platform:
  - x64

branches:
  only:
  - release

clone_depth: 3

environment:
  DEBUG: electron-windows-installer:main

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node '' x64
  - cmd: node -p "require('./package.json').version" > VERSION.txt
  - cmd: set /p NODE_PACKAGE_VERSION=<VERSION.txt
  - cmd: echo %NODE_PACKAGE_VERSION%
  - npm install npm --global
  - npm install
  - npm prune

test_script:
  - node --version
  - npm --version

build_script:
  - npm run-script build win32

build:
  publish_nuget: true
  verbosity: minimal

nuget:
  project_feed: true

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/65966d679f4ebeae4b3b   # Gitter
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

deploy:
  provider: GitHub
  description: 'Release'
  auth_token:
    secure: lCnXgfABbIDbDjEGA1FAVVPKmJkQ3PapIUJiGzFqP6lgz1q+oza9QSoN7eh74aip
  artifact: 'build\releases\pushbullet_for_desktop-win32-x64-v$(node_package_version).zip, build\releases\pushbullet_for_desktop-win32-ia32-v$(node_package_version).zip'
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: release
